In [3]:
import numpy as np 
import pandas as pd

# Creating a DataFrame

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
# using list -
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df=pd.DataFrame(data_list)
print(df)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [6]:
col = ["Name","Age","City","Salary"]
df=pd.DataFrame(data_list,columns=col)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000


# selection & indexing of coulumbs

In [7]:
df["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [9]:
df[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

# creating new columb

In [26]:
df["designation"]=["doctor","engineer","doctor","engineer"]
df

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000    engineer

# removing columbs

In [27]:
df.drop('designation',axis=1)                      # copy is created no updation!!

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000    engineer

In [29]:
df.drop('designation',axis=1,inplace=True)                       # updation permanently in df
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [34]:
df.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

# selecting row

In [35]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [36]:
df.loc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [37]:
#selecting subset of rows & columbs

In [39]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

# conditional selection in dataframes!!

In [44]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [52]:
# i want the age greater then 30 from the dataset -
df[df["Age"]>30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [53]:
# i want the age greater then 30 and city = paris -
df[(df["Age"]>30) & (df["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000