In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [3]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [5]:
X=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df['needs_water']

In [6]:
X

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [7]:
y

0     1
1     1
2     1
3     0
4     0
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    0
14    1
15    1
Name: needs_water, dtype: int64

In [8]:
# Normalization !!
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)


X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42 ,stratify=y)

In [10]:
model=keras.Sequential([
    layers.Input(shape = (X_scaled.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [14]:
model.compile(optimizer='sgd' ,loss='binary_crossentropy' ,metrics=['accuracy'])

In [16]:
# batch gradient descent
# history_full = model.fit(X_train, y_train, epochs=100, batch_size=len(X_train), verbose=1)

# stochastic gradient descent           [# batch_size=1]
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    batch_size=4,
    epochs=100,
    verbose=1
)

# MINI - BATCH gradient descent
# history_minibatch = model.fit(X_train, y_train, epochs=100, batch_size=100, verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.5977 - val_accuracy: 0.7500 - val_loss: 0.6317
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5967 - val_accuracy: 0.7500 - val_loss: 0.6310
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5958 - val_accuracy: 0.7500 - val_loss: 0.6302
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5950 - val_accuracy: 0.7500 - val_loss: 0.6294
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5943 - val_accuracy: 0.7500 - val_loss: 0.6287
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5934 - val_accuracy: 0.7500 - val_loss: 0.6279
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5929 - val_accuracy: 0.7500 - val_loss: 0.6272
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5918 - val_accuracy: 0.7500 - val_loss: 0.6264
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.5905 - val_accuracy: 0.7500 - val_loss: 0.6256
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5928 - val_accuracy: 0.7500 - val_loss: 0.6249
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5898 - val_accuracy: 0.7500 - val_loss: 0.6241
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5892 - val_accuracy: 0.7500 - val_loss: 0.6233
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5885 - val_accuracy: 0.7500 - val_loss: 0.6226
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5869 - val_accuracy: 0.7500 - val_loss: 0.6218
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5866 - val_accuracy: 0.7500 - val_loss: 0.6210
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5855 - val_accuracy: 0.7500 - val_loss: 0.6203
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8333 - loss: 0.5853 - val_accuracy: 0.7500 - val_loss: 0.6195
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5840 - val_accuracy: 0.7500 - val_loss: 0.6187
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5838 - val_accuracy: 0.7500 - val_loss: 0.6180
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5855 - val_accuracy: 0.7500 - val_loss: 0.6172
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5826 - val_accuracy: 0.7500 - val_loss: 0.6164
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5817 - val_accuracy: 0.7500 - val_loss: 0.6157
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8333 - loss: 0.5813 - val_accuracy: 0.7500 - val_loss: 0.6149
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5802 - val_accuracy: 0.7500 - val_loss: 0.6141
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5812 - val_accuracy: 0.7500 - val_loss: 0.6134
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5785 - val_accuracy: 0.7500 - val_loss: 0.6127
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5780 - val_accuracy: 0.7500 - val_loss: 0.6120
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5770 - val_accuracy: 0.7500 - val_loss: 0.6113
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5770 - val_accuracy: 0.7500 - val_loss: 0.6106
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5772 - val_accuracy: 0.7500 - val_loss: 0.6098
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5747 - val_accuracy: 0.7500 - val_loss: 0.6091
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8333 - loss: 0.5734 - val_accuracy: 0.7500 - val_loss: 0.6084
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5734 - val_accuracy: 0.7500 - val_loss: 0.6077
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5720 - val_accuracy: 0.7500 - val_loss: 0.6070
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5713 - val_accuracy: 0.7500 - val_loss: 0.6062
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.5704 - val_accuracy: 0.7500 - val_loss: 0.6055
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5697 - val_accuracy: 0.7500 - val_loss: 0.6048
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.5689 - val_accuracy: 0.7500 - val_loss: 0.6041
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5682 - val_accuracy: 0.7500 - val_loss: 0.6033
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5701 - val_accuracy: 0.7500 - val_loss: 0.6026
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.5672 - val_accuracy: 0.7500 - val_loss: 0.6019
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.5666 - val_accuracy: 0.7500 - val_loss: 0.6012
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.5657 - val_accuracy: 0.7500 - val_loss: 0.6004
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.5652 - val_accuracy: 0.7500 - val_loss: 0.5997
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.5637 - val_accuracy: 0.7500 - val_loss: 0.5990
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9167 - loss: 0.5630 - val_accuracy: 0.7500 - val_loss: 0.5983
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5628 - val_accuracy: 0.7500 - val_loss: 0.5975
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.5650 - val_accuracy: 0.7500 - val_loss: 0.5968
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5610 - val_accuracy: 0.7500 - val_loss: 0.5961
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.5600 - val_accuracy: 0.7500 - val_loss: 0.5953
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5614 - val_accuracy: 0.7500 - val_loss: 0.5946
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5595 - val_accuracy: 0.7500 - val_loss: 0.5939
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5585 - val_accuracy: 0.7500 - val_loss: 0.5932
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5577 - val_accuracy: 0.7500 - val_loss: 0.5924
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5592 - val_accuracy: 0.7500 - val_loss: 0.5917
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5561 - val_accuracy: 0.7500 - val_loss: 0.5910
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.5902
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5545 - val_accuracy: 0.7500 - val_loss: 0.5895
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.5539 - val_accuracy: 0.7500 - val_loss: 0.5888
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5533 - val_accuracy: 0.7500 - val_loss: 0.5880
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5525 - val_accuracy: 0.7500 - val_loss: 0.5873
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5513 - val_accuracy: 0.7500 - val_loss: 0.5866
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5502 - val_accuracy: 1.0000 - val_loss: 0.5858
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5501 - val_accuracy: 1.0000 - val_loss: 0.5851
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5497 - val_accuracy: 1.0000 - val_loss: 0.5844
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5487 - val_accuracy: 1.0000 - val_loss: 0.5836
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5484 - val_accuracy: 1.0000 - val_loss: 0.5829
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5471 - val_accuracy: 1.0000 - val_loss: 0.5822
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5463 - val_accuracy: 1.0000 - val_loss: 0.5814
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5449 - val_accuracy: 1.0000 - val_loss: 0.5807
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5448 - val_accuracy: 1.0000 - val_loss: 0.5799
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5440 - val_accuracy: 1.0000 - val_loss: 0.5792
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5435 - val_accuracy: 1.0000 - val_loss: 0.5785
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5430 - val_accuracy: 1.0000 - val_loss: 0.5777
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.5412 - val_accuracy: 1.0000 - val_loss: 0.5770
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.5415 - val_accuracy: 1.0000 - val_loss: 0.5762
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9167 - loss: 0.5411 - val_accuracy: 1.0000 - val_loss: 0.5755
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5420 - val_accuracy: 1.0000 - val_loss: 0.5748
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5394 - val_accuracy: 1.0000 - val_loss: 0.5740
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5376 - val_accuracy: 1.0000 - val_loss: 0.5732
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.5381 - val_accuracy: 1.0000 - val_loss: 0.5724
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5377 - val_accuracy: 1.0000 - val_loss: 0.5717
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9167 - loss: 0.5365 - val_accuracy: 1.0000 - val_loss: 0.5708
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5347 - val_accuracy: 1.0000 - val_loss: 0.5700
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5345 - val_accuracy: 1.0000 - val_loss: 0.5691
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5335 - val_accuracy: 1.0000 - val_loss: 0.5683
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5355 - val_accuracy: 1.0000 - val_loss: 0.5675
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9167 - loss: 0.5322 - val_accuracy: 1.0000 - val_loss: 0.5667
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5311 - val_accuracy: 1.0000 - val_loss: 0.5658
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5312 - val_accuracy: 1.0000 - val_loss: 0.5650
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9167 - loss: 0.5304 - val_accuracy: 1.0000 - val_loss: 0.5641
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5297 - val_accuracy: 1.0000 - val_loss: 0.5633
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5293 - val_accuracy: 1.0000 - val_loss: 0.5625
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5280 - val_accuracy: 1.0000 - val_loss: 0.5617
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5277 - val_accuracy: 1.0000 - val_loss: 0.5608
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9167 - loss: 0.5261 - val_accuracy: 1.0000 - val_loss: 0.5600
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9167 - loss: 0.5274 - val_accuracy: 1.0000 - val_loss: 0.5592
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.5255 - val_accuracy: 1.0000 - val_loss: 0.5584
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.5239 - val_accuracy: 1.0000 - val_loss: 0.5575
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5238 - val_accuracy: 1.0000 - val_loss: 0.5567

In [1]:
#MOMENTUM WITH SGD!!
from tensorflow.keras import optimizers

opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)

In [18]:
model.compile(optimizer=opt ,loss='binary_crossentropy' ,metrics=['accuracy'])

In [19]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    batch_size=1,
    epochs=100,
    verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7500 - loss: 0.5438 - val_accuracy: 1.0000 - val_loss: 0.5449
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.4978 - val_accuracy: 1.0000 - val_loss: 0.5192
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4893 - val_accuracy: 1.0000 - val_loss: 0.4878
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5042 - val_accuracy: 1.0000 - val_loss: 0.4577
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.4367 - val_accuracy: 1.0000 - val_loss: 0.4233
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.4279 - val_accuracy: 1.0000 - val_loss: 0.4309
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.4047 - val_accuracy: 1.0000 - val_loss: 0.3640
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3871 - val_accuracy: 1.0000 - val_loss: 0.3362
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.3924 - val_accuracy: 1.0000 - val_loss: 0.3458
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.3411 - val_accuracy: 1.0000 - val_loss: 0.2888
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3410 - val_accuracy: 1.0000 - val_loss: 0.2855
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3241 - val_accuracy: 1.0000 - val_loss: 0.2776
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.2900 - val_accuracy: 1.0000 - val_loss: 0.2547
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.2999 - val_accuracy: 1.0000 - val_loss: 0.2269
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.2639 - val_accuracy: 1.0000 - val_loss: 0.2415
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.2644 - val_accuracy: 1.0000 - val_loss: 0.2491
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.2627 - val_accuracy: 1.0000 - val_loss: 0.2161
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.2493 - val_accuracy: 1.0000 - val_loss: 0.2133
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.2360 - val_accuracy: 1.0000 - val_loss: 0.2014
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2259 - val_accuracy: 1.0000 - val_loss: 0.1921
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.2484 - val_accuracy: 1.0000 - val_loss: 0.2384
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.2073 - val_accuracy: 1.0000 - val_loss: 0.1876
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.2547 - val_accuracy: 1.0000 - val_loss: 0.1505
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.1771 - val_accuracy: 1.0000 - val_loss: 0.2020
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.2971 - val_accuracy: 1.0000 - val_loss: 0.2158
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.2204 - val_accuracy: 1.0000 - val_loss: 0.1480
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1970 - val_accuracy: 1.0000 - val_loss: 0.2056
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.1965 - val_accuracy: 1.0000 - val_loss: 0.1665
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1748 - val_accuracy: 1.0000 - val_loss: 0.1732
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1746 - val_accuracy: 1.0000 - val_loss: 0.1723
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1685 - val_accuracy: 1.0000 - val_loss: 0.1499
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1763 - val_accuracy: 0.7500 - val_loss: 0.2059
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1569 - val_accuracy: 1.0000 - val_loss: 0.1614
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1616 - val_accuracy: 1.0000 - val_loss: 0.1571
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1641 - val_accuracy: 1.0000 - val_loss: 0.1561
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.1629 - val_accuracy: 0.7500 - val_loss: 0.2106
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1424 - val_accuracy: 1.0000 - val_loss: 0.1740
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1361 - val_accuracy: 1.0000 - val_loss: 0.1445
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1780 - val_accuracy: 0.7500 - val_loss: 0.1989
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1221 - val_accuracy: 1.0000 - val_loss: 0.1543
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1376 - val_accuracy: 1.0000 - val_loss: 0.1698
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1373 - val_accuracy: 0.7500 - val_loss: 0.1864
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1716 - val_accuracy: 1.0000 - val_loss: 0.1545
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.1678 - val_accuracy: 0.7500 - val_loss: 0.2147
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1391 - val_accuracy: 1.0000 - val_loss: 0.1285
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1367 - val_accuracy: 1.0000 - val_loss: 0.1699
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1139 - val_accuracy: 1.0000 - val_loss: 0.1771
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1242 - val_accuracy: 1.0000 - val_loss: 0.1508
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1499 - val_accuracy: 0.7500 - val_loss: 0.2165
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1078 - val_accuracy: 1.0000 - val_loss: 0.1322
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1179 - val_accuracy: 1.0000 - val_loss: 0.1780
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1144 - val_accuracy: 1.0000 - val_loss: 0.1445
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1439 - val_accuracy: 1.0000 - val_loss: 0.1398
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1676 - val_accuracy: 0.7500 - val_loss: 0.2191
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.1672 - val_accuracy: 1.0000 - val_loss: 0.0996
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1017 - val_accuracy: 1.0000 - val_loss: 0.1463
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1088 - val_accuracy: 1.0000 - val_loss: 0.1408
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0968 - val_accuracy: 1.0000 - val_loss: 0.1398
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.1192 - val_accuracy: 1.0000 - val_loss: 0.1688
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.1289 - val_accuracy: 1.0000 - val_loss: 0.0983
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0913 - val_accuracy: 1.0000 - val_loss: 0.1773
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1161 - val_accuracy: 1.0000 - val_loss: 0.1260
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0953 - val_accuracy: 1.0000 - val_loss: 0.1578
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0953 - val_accuracy: 1.0000 - val_loss: 0.1587
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1020 - val_accuracy: 1.0000 - val_loss: 0.1329
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0854 - val_accuracy: 1.0000 - val_loss: 0.1487
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0951 - val_accuracy: 1.0000 - val_loss: 0.1404
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0817 - val_accuracy: 1.0000 - val_loss: 0.1270
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0965 - val_accuracy: 0.7500 - val_loss: 0.1814
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1056 - val_accuracy: 1.0000 - val_loss: 0.1288
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0894 - val_accuracy: 0.7500 - val_loss: 0.1797
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1169 - val_accuracy: 1.0000 - val_loss: 0.1150
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0761 - val_accuracy: 0.7500 - val_loss: 0.1866
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.1012 - val_accuracy: 1.0000 - val_loss: 0.1119
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0768 - val_accuracy: 1.0000 - val_loss: 0.1139
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0739 - val_accuracy: 1.0000 - val_loss: 0.1492
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0815 - val_accuracy: 1.0000 - val_loss: 0.1652
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0744 - val_accuracy: 1.0000 - val_loss: 0.0899
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0833 - val_accuracy: 1.0000 - val_loss: 0.1392
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.0956 - val_accuracy: 1.0000 - val_loss: 0.1570
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0821 - val_accuracy: 1.0000 - val_loss: 0.1137
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0693 - val_accuracy: 1.0000 - val_loss: 0.1252
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0851 - val_accuracy: 1.0000 - val_loss: 0.1543
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0665 - val_accuracy: 1.0000 - val_loss: 0.1162
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0722 - val_accuracy: 1.0000 - val_loss: 0.1430
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0620 - val_accuracy: 1.0000 - val_loss: 0.1621
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0688 - val_accuracy: 1.0000 - val_loss: 0.1461
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0654 - val_accuracy: 1.0000 - val_loss: 0.1497
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0594 - val_accuracy: 1.0000 - val_loss: 0.1385
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0633 - val_accuracy: 1.0000 - val_loss: 0.1667
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0843 - val_accuracy: 1.0000 - val_loss: 0.1465
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0767 - val_accuracy: 0.7500 - val_loss: 0.1786
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0905 - val_accuracy: 1.0000 - val_loss: 0.1055
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0570 - val_accuracy: 1.0000 - val_loss: 0.1360
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0744 - val_accuracy: 1.0000 - val_loss: 0.1492
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0721 - val_accuracy: 1.0000 - val_loss: 0.0907
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0499 - val_accuracy: 1.0000 - val_loss: 0.1227
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.0801 - val_accuracy: 1.0000 - val_loss: 0.1566
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1042 - val_accuracy: 1.0000 - val_loss: 0.0806
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0615 - val_accuracy: 1.0000 - val_loss: 0.1367